sudo: required
language: java

jdk:
  - openjdk8

services:
  - docker

script:
  - mvn clean package -U
  - docker build -t zigakern/streaming_service:v0.1.0 .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push zigakern/streaming_service:v0.1.0