version: "3.2"
services:
  streaming_service:
    image: zigakern/streaming_service:v0.1.0
    ports:
      - 8083:8083
    environment:
      - KUMULUZEE_SERVER_BASE-URL=http://192.168.99.100:8083
    volumes:
      - type: volume
        target: /data
        source: clipFile_db

volumes:
    clipFile_db: